### ISSUE TITLE
Can't find "ldscript_memspecific.ld" file

### ISSUE THREAD

**Issue by harrzz** [Spritetm/esphttpd#1]
Hallo, maybe I'm wrong. But I can't find the "ldscript_memspecific.ld" file. Is the file from a specific sdk?

**Comment by Spritetm** [comment]
It should be autogenerated. Does make complain it's not there?

**Comment by Spritetm** [comment]
Ah check, seems I forgot the generation code in the 'separate' makefile. Fixed in  24e00aa7e11a243069408b2893ff8c16ed4c3ae6
